---
#Desactivo los detalles de la request
enableLoggingRequestDetails: false
server:
  error:
    #Al haber un error envia siempre message y los parametros
    include-message: always
    include-binding-errors: always
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss


spring:
  main:
    banner-mode: off
...