---
#Desactivo los detalles de la request
enableLoggingRequestDetails: false
server:
  error:
    #Al haber un error envia siempre message y los parametros
    include-message: always
    include-binding-errors: always
#Se asigna los niveles de Logging para mensajes en consola
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  #Cambio el formato de la hora en consola
  pattern:
    dateformat: HH:mm:ss


spring:
  main:
    #Desactivo el Banner de Spring Booy de consola
    banner-mode: off
  #Configuracion de conex
  security:
    oauth2:
      resourceserver:
  jwt:
    issuer-uri: https://securetoken.google.com/quizz-app-77eb3
    jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

...